services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/storage/downloads/shows/config:/config
      - /mnt/storage/downloads/shows:/tv #optional
    ports:
      - 2028:8989
    restart: always
