workers:
  hosts:
    worker_1:
      ansible_host: 10.12.40.101
    worker_2:
      ansible_host: 10.12.40.102
    worker_3:
      ansible_host: 10.12.40.103
  vars:
    ansible_user: "{{ ansible_ansible_user }}"
    ansible_port: 1122
    api_token: "{{ ansible_api_token }}"
