services:
    prometheus:
        image: prom/prometheus
        ports:
            - 4446:9090
        volumes:
            - prometheus-data:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        extra_hosts:
            - "host.docker.internal=host-gateway"
    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        command:
            - '--path.rootfs=/host'
        ports:
            - 9111:9100
        pid: host
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'
volumes:
    prometheus-data:
        external: true
        name: prometheus-data
