networks:
  loki:


services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "4445:3100"
    volumes:
      - ./loki.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://192.168.0.199:4445
          basicAuth: false
          isDefault: false
          version: 1
          editable: true
        - name: Prometheus
          type: prometheus
          access: proxy
          orgId: 1
          url: http://192.168.0.199:4446
          basicAuth: false
          isDefault: true
          version: 1
          editable: true
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "4444:3000"
    networks:
      - loki
