services:
    pgvecto-17:
        image: tensorchord/pgvecto-rs:pg16-v0.3.0
        ports:
            - 9113:5432
        environment:
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_INITDB_ARGS: '--data-checksums'
        volumes:
          - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
          - ./postgres.conf:/etc/postgresql/postgresql.conf
        restart: always
