services:
    portainer-agent:
        image: portainer/agent:latest
        ports:
            - 9444:9001
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        restart: always

