networks:
  monitoring:
    driver: bridge

services:
  alloy:
    image: grafana/alloy:latest  # Replace with the actual Alloy image
    container_name: monitoring-alloy
    environment:
      - ALLOY_METRICS_PORT=8080      # Metric port, change as necessary
      - ALLOY_LOGS_PORT=8081         # Log port, change as necessary
    ports:
      - "4446:8080"                  # Metrics port for Alloy
      - "4447:8081"                  # Logs port for Alloy
      - "4448:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy    # Mount custom configuration if needed
    networks:
      - monitoring
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: monitoring-loki
    ports:
      - "4445:3100"
    volumes:
      - ./loki.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring-grafana
    depends_on:
      - loki
      - alloy
    ports:
      - "4444:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - monitoring
    restart: unless-stopped

volumes:
    prometheus-data:
        external: true
        name: prometheus-data

