networks:
  monitoring:
    driver: bridge

services:
  alloy:
    image: grafana/alloy:latest
    environment:
      - ALLOY_METRICS_PORT=8080      # Metric port, change as necessary
      - ALLOY_LOGS_PORT=8081         # Log port, change as necessary
    ports:
      - "4446:8080"                  # Metrics port for Alloy
      - "4447:8081"                  # Logs port for Alloy
      - "12345:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy    # Mount custom configuration if needed
    networks:
      - monitoring
    restart: unless-stopped
