---
- name: Update and Upgrade
  hosts: all
  become: yes

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Perform dist-upgrade
      apt:
        upgrade: full
