---
- name: Enable Automatic Updates on Debian
  hosts: all
  become: yes

  tasks:
    - name: Install unattended-upgrades package
      apt:
        name: unattended-upgrades
        state: present

    - name: Install apt-listchanges package
      apt:
        name: apt-listchanges
        state: present

    - name: Enable automatic updates
      lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        create: yes
        line: 'APT::Periodic::Update-Package-Lists "1";'
        state: present

    - name: Enable periodic unattended upgrades
      lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        line: 'APT::Periodic::Unattended-Upgrade "1";'
        state: present

    - name: Enable unattended-upgrades service
      systemd:
        name: unattended-upgrades
        enabled: yes
        state: started
